# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Dreamfish
subtitle: ''
description: '‰∫∫ÁîüÂ§©Âú∞Èó¥ÔºåÂøΩÂ¶ÇËøúË°åÂÆÄÄ?'
keywords: 
author: Ê¢¶È±º
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://dreamfish.cc/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: 'git'
  repository: git@github.com:dreamfishyx/dreamfishyx.github.io.git
  branch: main

markdown:
    plugins:
      - '@renbaoshuo/markdown-it-katex'

feed:
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

aplayer:
  meting: true
  asset_inject: false

artitalk:
    enable: true
    appId: TLDc9eD2s9EBERu9vooTVSyR-MdYXbMMI
    appKey: jKiscAw16nG6KjyuHVFkiNYb
    path: 
    js: https://cdn.jsdelivr.net/gh/dreamfishyx/mycdn/js/artitalk.js
    option:
      avatarPla: 'https://cdn.jsdelivr.net/gh/dreamfishyx/pictures@main/img/2024-04-06-16-47-19-d291bc.jpg'
      shuoPla: "ËØ¥ÁÇπ‰ªÄ‰πàÂêß~"
      atEmoji: 
        baiyan: "https://cdn.jsdelivr.net/gh/Artitalk/Artitalk-emoji/baiyan.png"
        bishi: "https://cdn.jsdelivr.net/gh/Artitalk/Artitalk-emoji/bishi.png"
        bizui: "https://cdn.jsdelivr.net/gh/Artitalk/Artitalk-emoji/bizui.png"
        chan: "https://cdn.jsdelivr.net/gh/Artitalk/Artitalk-emoji/chan.png"
        daku: "https://cdn.jsdelivr.net/gh/Artitalk/Artitalk-emoji/daku.png"
        dalao: "https://cdn.jsdelivr.net/gh/Artitalk/Artitalk-emoji/dalao.png"
        dalian: "https://cdn.jsdelivr.net/gh/Artitalk/Artitalk-emoji/dalian.png"
        dianzan: "https://cdn.jsdelivr.net/gh/Artitalk/Artitalk-emoji/dianzan.png"
        doge: "https://cdn.jsdelivr.net/gh/Artitalk/Artitalk-emoji/doge.png"
        facai: "https://cdn.jsdelivr.net/gh/Artitalk/Artitalk-emoji/facai.png"
        fadai: "https://cdn.jsdelivr.net/gh/Artitalk/Artitalk-emoji/fadai.png"
        fanu: "https://cdn.jsdelivr.net/gh/Artitalk/Artitalk-emoji/fanu.png"
      pageSize: 7
    front_matter:
      comments: false

sitemap:
  path: sitemap.xml

baidusitemap:
  path: baidusitemap.xml